---
# tasks file for grafana
#
- name: add grafana gpg key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: grafana repo
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
- name: install grafana package
  package:
    name: "grafana"
    state: present
  tags:
    - install_packages
- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started
- name: install promethus
  package:
    name: "prometheus"
    state: present
- name: Enable and start prometheus service
  service:
    name: prometheus
    enabled: yes
    state: started
- name: copy promethus config file
  copy:
    src: files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
  notify: 
    - restart prometheus.service
